from django.shortcuts import resolve_url

class AppBasedRedirectMiddleware:
    """
    Middleware to handle app-based redirection for incoming requests.

    This middleware checks if the request path starts with '/project/'.
    If it does, it sets the 'login_redirect' session variable to the URL
    resolved by 'recipe_list'.

    Attributes:
        get_response (callable): The next middleware or view in the chain.

    Methods:
        __call__(request):
            Processes the incoming request and applies the redirection logic.
    """

    """
    Initializes the middleware with the given response handler.

    Args:
        get_response (callable): The next middleware or view in the chain.
    """

    """
    Processes the incoming request and applies the redirection logic.

    Args:
        request (HttpRequest): The incoming HTTP request.

    Returns:
        HttpResponse: The response generated by the next middleware or view.
    """
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        if request.path.startswith('/project/'):
            request.session['login_redirect'] = resolve_url('recipe_list')
        return self.get_response(request)
