from django.urls import path
from .views import (
    HomePageView,
    RecipeListView,
    RecipeDetailView,
    CategoryListView,
    CategoryDetailView,
    CustomLoginView,
    ProfileCreateView,
    ProfileDetailView,
    ProfileOnlyCreateView,
    CustomLogoutView,
    CommentUpdateView,
    CommentDeleteView,
    RecipeCreateView,
    MyRecipesView,
    ToggleFavoriteView,
    RecipeCreateView,
    RecipeUpdateView,
    RecipeDeleteView,
)

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('recipes/', RecipeListView.as_view(), name='recipe_list'),
    path('recipe/<int:pk>/', RecipeDetailView.as_view(), name='recipe_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('profile/create/', ProfileCreateView.as_view(), name='profile_create'),
    path('profile/<int:pk>/', ProfileDetailView.as_view(), name='profile_detail'),
    path('login/', CustomLoginView.as_view(), name='project_login'),
    path('logout/', CustomLogoutView.as_view(), name='project_logout'),
    path('profile/create-only/', ProfileOnlyCreateView.as_view(), name='profile_create_only'),
    path('comment/<int:pk>/edit/', CommentUpdateView.as_view(), name='comment_edit'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('my-recipes/', MyRecipesView.as_view(), name='my_recipes'),
    path('recipe/<int:pk>/favorite/', ToggleFavoriteView.as_view(), name='toggle_favorite'),
    path('recipe/create/', RecipeCreateView.as_view(), name='recipe_create'),
    path('recipe/<int:pk>/edit/', RecipeUpdateView.as_view(), name='recipe_update'),
    path('recipe/<int:pk>/delete/', RecipeDeleteView.as_view(), name='recipe_delete'),
]